//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Cal3DViewer.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MYCal3DViewer_DIALOG        102
#define IDR_MAINFRAME                   128
#define IDD_ADD                         194
#define IDB_ADDDOWN                     195
#define IDB_ADDUP                       196
#define IDB_CLOSEDOWN                   197
#define IDB_CLOSEUP                     198
#define IDB_TEXTUREDLINEDOWN            199
#define IDB_TEXTUREDLINEUP              200
#define IDB_DELETEDOWN                  201
#define IDB_DOWN                        203
#define IDB_HOMEDOWN                    204
#define IDB_HOMEUP                      205
#define IDB_INTERACTIVEDOWN             206
#define IDB_INTERACTIVEUP               207
#define IDB_LEFT                        208
#define IDB_MINIMIZEDOWN                209
#define IDB_MINIMIZEUP                  210
#define IDB_NEXTDOWN                    211
#define IDB_NEXTUP                      212
#define IDB_PREVDOWN                    213
#define IDB_PREVUP                      214
#define IDB_RIGHT                       215
#define IDB_ROTATEDOWN                  216
#define IDB_ROTATEUP                    217
#define IDB_SOLIDDOWN                   218
#define IDB_SOLIDUP                     219
#define IDB_STOPDOWN                    220
#define IDB_STOPUP                      221
#define IDB_TEXTUREDPOINTDOWN           222
#define IDB_TEXTUREDPOINTUP             223
#define IDB_TOP                         224
#define IDB_WHITELINEDOWN               225
#define IDB_WHITELINEUP                 226
#define IDB_WHITEPOINTDOWN              227
#define IDB_WHITEPOINTUP                228
#define IDB_DELETEUP                    232
#define IDB_STOPDISABLE                 234
#define IDB_HELPDOWN                    235
#define IDB_HELPUP                      236
#define IDB_INFODOWN                    237
#define IDB_INFOUP                      238
#define IDB_NEXTDISABLE                 239
#define IDB_PREVDISABLE                 240
#define IDB_DFLT                        241
#define IDB_SMALLIMG                    243
#define IDC_MOVE                        247
#define IDC_PAN                         248
#define IDC_ZOOM                        249
#define IDC_INVALID                     251
#define IDB_WHITEPOINTF                 253
#define IDB_ADDF                        254
#define IDB_TEXTUREDLINEF               255
#define IDB_DELETEF                     256
#define IDB_HOMEF                       257
#define IDB_INTERACTIVEF                258
#define IDB_NEXTF                       259
#define IDB_PREVF                       260
#define IDB_ROTATEF                     261
#define IDB_SOLIDF                      262
#define IDB_STOPF                       263
#define IDB_TEXTUREDPOINTF              264
#define IDB_WHITELINEF                  265
#define IDB_WHITEPOINTDISABLE           266
#define IDB_TEXTUREDLINEDISABLE         267
#define IDB_DELETEDISABLE               268
#define IDB_HOMEDISABLE                 269
#define IDB_INTERACTIVEDISABLE          270
#define IDB_ROTATEDISABLE               271
#define IDB_SOLIDDISABLE                272
#define IDB_TEXTUREDPOINTDISABLE        273
#define IDB_WHITELINEDISABLE            274
#define IDB_SAVEUP                      275
#define IDB_SAVEDOWN                    276
#define IDB_SAVEDISABLE                 277
#define IDB_SAVEF                       278
#define IDD_HELP                        279
#define IDB_HELP                        280
#define IDB_THUMB_ACTIVE                281
#define IDB_CHANNEL                     282
#define IDB_CHANNEL_ACTIVE              283
#define IDB_THUMB                       284
#define IDB_NEXTANIM_UP                 286
#define IDB_NEXTANIM_DOWN               287
#define IDB_NEXTANIM_F                  288
#define IDB_NEXTANIM_DISABLE            290
#define IDB_PREVANIM_DOWN               291
#define IDB_PREVANIM_DISABLE            292
#define IDB_PREVANIM_F                  293
#define IDB_PREVANIM_UP                 294
#define IDB_DFLTIMG                     295
#define IDB_BITMAP1                     296
#define IDB_ABOUTUP                     296
#define IDB_BITMAP2                     297
#define IDB_ABOUTDOWN                   297
#define IDD_INFO                        298
#define IDD_DIALOG_REOMMENDED_SOFTWARE  299
#define IDB_BITMAP3                     300
#define IDB_BITMAP_VANDA_ENGINE         300
#define IDC_CLOSE                       1006
#define IDC_NEXT                        1007
#define IDC_LIST1                       1008
#define IDC_PREV                        1009
#define IDC_STOP                        1011
#define IDC_PLAY                        1012
#define IDC_ROTATE                      1013
#define IDC_INTERACTIVE                 1014
#define IDC_INFO                        1015
#define IDC_MYHELP                      1016
#define IDC_WHITEPOINTS                 1017
#define IDC_PHOTO                       1018
#define IDC_NEXTANIMATION               1019
#define IDC_PREVANIMATION               1020
#define IDC_ABOUT                       1021
#define IDC_BONE                        1024
#define IDC_WHITELINES                  1026
#define IDC_TEXTUREDLINES               1027
#define IDC_OPENMODEL                   1027
#define IDC_SOLID                       1028
#define IDC_OPENBMP                     1028
#define IDC_OK                          1029
#define IDC_ADDMODEL                    1029
#define IDC_SAVEDB                      1030
#define IDC_CLOSEHELP                   1030
#define IDC_HOME                        1031
#define IDC_SAVELIST                    1032
#define IDC_MINIMIZE                    1034
#define IDC_SLIDER                      1036
#define IDC_RENDERER                    1037
#define IDC_VERSION                     1038
#define IDC_REMOVEMODEL                 1039
#define IDC_SHADINGVERSION              1039
#define IDC_EDIT1                       1040
#define IDC_MFCLINK1                    1040
#define IDC_EDIT2                       1041
#define IDC_MFCLINK2                    1041
#define IDC_EDIT3                       1042
#define IDC_CHECK1                      1042
#define IDC_CHECK                       1042
#define IDC_VENDOR                      1043
#define IDC_NUMVERTICES                 1044
#define IDC_NUMFACES                    1045
#define IDC_NUMANIMATIONS               1046
#define IDC_LODLEVEL                    1047
#define IDC_NUMMESHES                   1048
#define IDC_NUMMATERIALS                1049
#define IDC_EXTENSIONS                  1050

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        302
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1043
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
